### ISSUE TITLE
Drop tags for Nette 2.4

### ISSUE THREAD

**Issue by mabar** [iPublikuj/WidgetsManager#4]
Tags are no more required. If widgets are descendants of iPub\Widgets everytime, so `$this->container->findByTag('ipub.widgets.widget');` should be replaced by `$this->container->findAllByType(WidgetClass::class);`

Otherwise, descendants of iPub\Widgets should use decorator
```yml
decorator:
    IPub\Widgets\Widgets\Component:
        tags: [ipub.widgets.widget]
```
